### ISSUE TITLE
dmx_receiver does not start in current HAOS 10.5

### ISSUE THREAD

**Issue by MrDionysus** [Azimath/Azimath-HA-Addons#1]
Hey there, I'm not sure if development has stopped for this receiver, but if you're still working on it then I'd be most grateful if you can advise on anything to change to get around this error when I try to start the receiver addon in HAOS 10.5:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
{
  "universe": 1,
  "map": [
    {
      "entity": "light.controller_rgb_ir_mini_1199f9",
      "channels": [
        1,
        2,
        3
      ]
    }
  ]
Traceback (most recent call last):
  File "/dmx_receive.py", line 77, in <module>
}Starting DMX receiver
Connecting to HA with URL http://supervisor/core/api
Connected to HA!
    light = client.get_domain(domain_id="light")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/homeassistant_api/rawclient.py", line 249, in get_domain
    return self.get_domains().get(domain_id)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/homeassistant_api/rawclient.py", line 245, in get_domains
    return {domain.domain_id: domain for domain in domains}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/homeassistant_api/rawclient.py", line 245, in <dictcomp>
    return {domain.domain_id: domain for domain in domains}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/homeassistant_api/rawclient.py", line 242, in <lambda>
    lambda json: Domain.from_json(json, client=cast(Client, self)),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/homeassistant_api/models/domains.py", line 46, in from_json
    domain._add_service(service_id, **data)
  File "/usr/lib/python3.11/site-packages/homeassistant_api/models/domains.py", line 53, in _add_service
    service_id: Service(
                ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/main.py", line 331, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Service
target -> entity
  value is not a valid dict (type=type_error.dict)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

My config yaml is as follows:
```
universe: 1
map:
  - entity: light.controller_rgb_ir_mini_1199f9
    channels:
      - 1
      - 2
      - 3
```

Thanks!

**Comment by Azimath** [comment]
I haven't touched it in a while but will have a look when I get a chance,
hopefully soon.

**Comment by MrDionysus** [comment]
I really appreciate it.  I suspect the problem is probably a syntax change with newer versions of python, but I can't seem to nail down which one works.  If you happen to know the last python version that worked with it, please let me know and I'll try that!

**Comment by Azimath** [comment]
Looks like I just need to have it run the latest homeassistant-api. I have a new version up but I've been having some new problems getting the python script to actually start up.

**Comment by Azimath** [comment]
Ok go ahead and give v 1.0.8 a shot

**Comment by MrDionysus** [comment]
So far it looks good!  The service has started and is running, now I can try sending some sacn messages to it.  I will attempt this either tonight or tomorrow morning.  Thank you, once again, for doing this!

**Comment by MrDionysus** [comment]
Confirmed working with sacn calls to the three channels, you're the best!
